; This file was auto-generated by drush make
core = 7.x
api = 2
projects[drupal][version] = "7.23"

; Modules
projects[views_bulk_operations][subdir] = "contrib"

projects[backup_migrate][subdir] = "contrib"

projects[bean][subdir] = "contrib"

projects[block_class][subdir] = "contrib"

projects[blockreference][subdir] = "contrib"

projects[bootstrap_carousel][subdir] = "contrib"

projects[ctools][subdir] = "contrib"

projects[cck][subdir] = "contrib"

projects[context][subdir] = "contrib"

projects[date][subdir] = "contrib"

projects[diff][subdir] = "contrib"

projects[email][subdir] = "contrib"

projects[entity][subdir] = "contrib"

projects[eva][subdir] = "contrib"

projects[features][subdir] = "contrib"

projects[field_collection][subdir] = "contrib"
projects[field_group][subdir] = "contrib"

projects[media][subdir] = "contrib"

projects[filter_perms][subdir] = "contrib"

projects[globalredirect][subdir] = "contrib"

projects[google_appliance][subdir] = "contrib"
projects[google_analytics][subdir] = "contrib"

projects[grammar_parser_lib][subdir] = "contrib"

projects[hierarchical_select][subdir] = "contrib"

projects[imagecrop][subdir] = "contrib"

projects[imagefield_crop][subdir] = "contrib"

projects[imce][subdir] = "contrib"
projects[imce_wysiwyg][subdir] = "contrib"

projects[job_scheduler][subdir] = "contrib"

projects[jscrollpane][subdir] = "contrib"
projects[jquery_update][subdir] = "contrib"

projects[libraries][subdir] = "contrib"

projects[lightbox2][subdir] = "contrib"

projects[link][subdir] = "contrib"

projects[mail_edit][subdir] = "contrib"
projects[mailsystem][subdir] = "contrib"

projects[menu_block][subdir] = "contrib"

projects[menu_position][subdir] = "contrib"

projects[mimemail][subdir] = "contrib"

projects[mollom][subdir] = "contrib"

projects[references][subdir] = "contrib"

projects[nodereference_url][subdir] = "contrib"

projects[options_element][subdir] = "contrib"

projects[pathauto][subdir] = "contrib"

projects[phone][subdir] = "contrib"

projects[quicktabs][subdir] = "contrib"

projects[realname][subdir] = "contrib"

projects[redirect][subdir] = "contrib"

projects[remember_me][subdir] = "contrib"

projects[rules][subdir] = "contrib"

projects[secure_permissions][subdir] = "contrib"
projects[securepages][subdir] = "contrib"

projects[special_menu_items][subdir] = "contrib"

projects[strongarm][subdir] = "contrib"

projects[taxonomy_access][subdir] = "contrib"
projects[taxonomy_menu][subdir] = "contrib"

projects[token][subdir] = "contrib"

projects[views][subdir] = "contrib"
projects[views_accordion][subdir] = "contrib"

projects[views_data_export][subdir] = "contrib"

projects[webform][subdir] = "contrib"
projects[wysiwyg][subdir] = "contrib"

projects[bootstrap] = "2.1"
projects[omega] = "3.1"
projects[rubik] = "4.0-beta8"
projects[tao] = "3.0-beta4"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = "zip"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%204.2/ckeditor_4.2_standard.zip"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"
